### ISSUE TITLE
May I use some of your luasnip in my plugin?

### ISSUE THREAD

**Issue by ray-x** [arsham/shark#2]
I really love your snip setup for go. Great work.
I would like to use those code in my plugin and I have a PR here:
https://github.com/ray-x/go.nvim/pull/165
I noticed there is no licence agreement in your repo. So need to confirm may I copy those codes across to my plugin (MIT licence)?

**Comment by arsham** [comment]
Hi mate, thanks for your comment.
You have my blessing! I will add a license shortly.

**Comment by ray-x** [comment]
Thanks! That will save me lots of time.
